/**
 * A coordinator
 *
 * @author <a href="mailto:emericv@mbedsys.fr">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface Coordinator {
	/**
	 * Pairing window time. Integer value within 0 and 255 seconds
	 */
	readonly attribute unsigned long pairingWindowTime;

	/**
	 * Pairing window state. Boolean value, true for open
	 */
	readonly attribute boolean pairingWindowState;

	/**
	 * Open pairing window
	 * 
	 * @param time Integer value within 0 and 255 seconds
	 */
	void openWindow(in unsigned long time);

	/**
	 * Open pairing window
	 * 
	 * @param time Integer value within 0 and 255 seconds
	 */
	void openWindowExt(in unsigned long time, in boolean softMode, in boolean keepOpen);

	/**
	 * Close pairing window
	 */
	void closeWindow();

	/**
	 * Reset network
	 */
	void resetNetwork();
};
