/**
 * 
 * 
 * @author <a href="mailto:emericv@mbedsys.fr">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface DeviceInfo {

	/**
	 * Vendor name
	 */
	readonly attribute string vendorName;

	/**
	 * Vendor ID
	 */
	readonly attribute string vendorId;

	/**
	 * Model name
	 */
	readonly attribute string modelName;

	/**
	 * Model ID
	 */
	readonly attribute string modelId;

	/**
	 * Protocol version
	 */
	readonly attribute string protocolVersion;

	/**
	 * Stack version
	 */
	readonly attribute string stackVersion;

	/**
	 * Hardware version
	 */
	readonly attribute string hardwareVersion;

	/**
	 * Software version
	 */
	readonly attribute string softwareVersion;

	/**
	 * Power source
	 */
	readonly attribute unsigned int powerSource;
	
	/**
	 * PowerSource: Unknown
	 */
	const octet POWER_SOURCE_UNKNOW = 0x00;
	
	/**
	 * PowerSource: Single phase alternating current.
	 */
	const octet POWER_SOURCE_AC_1P = 0x01;
	
	/**
	 * PowerSource: Three phase alternating current.
	 */
	const octet POWER_SOURCE_AC_3P = 0x02;
	
	/**
	 * PowerSource: Battery
	 */
	const octet POWER_SOURCE_BATTERY = 0x03;
	
	/**
	 * PowerSource: Direct current.
	 */
	const octet POWER_SOURCE_DC = 0x04;

};
