/**
 * This interface defines a dimmer
 * 
 * @author <a href="mailto:emericv@mbedsys.fr">Emeric Verschuur</a>
 *         Copyright 2014 MbedSYS
 */
interface Dimmer {

	/**
	 * Level value in percent (data type: number between 0 and 100)
	 */
	attribute unsigned long level;
};
