#include <SecuritySensor.idl> 

/**
 * A motion sensor
 * 
 * @author <a href="mailto:emericv@mbedsys.org">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface MotionSensor : SecuritySensor {

	/**
	 * intrusion indicator
	 */
	readonly attribute  boolean intrusionInd;

	/**
	 * presence indicator
	 */
	readonly attribute  boolean presenceInd;
};
