/**
 * A power supply
 * 
 * @author <a href="mailto:emericv@mbedsys.org">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface PowerSupply {

	/**
	 * Low battery indicator
	 */
	readonly attribute boolean lowBattery;
};
