/**
 * A service status
 * 
 * @author <a href="mailto:emericv@mbedsys.fr">Emeric Verschuur</a>
 *         Copyright 2014 MbedSYS
 */
interface ServiceStatus {

	/**
	 * Time in second between 1970-01-01 00:00:00 of the last
	 * transmission from the device
	 */
	readonly attribute unsigned long long lastActivityTime;

	/**
	 * Inactivity time between the last device activity in
	 * minutes
	 */
	readonly attribute unsigned long idleTime;

	/**
	 * Device offline indicator
	 */
	readonly attribute boolean offlineInd;

	/**
	 * Leave this device
	 */
	void leave();

};
