#include <SwitchSensor.idl> 

/**
 * A switch command
 * 
 * @author <a href="mailto:emericv@mbedsys.fr">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface SwitchCmd : SwitchSensor {
	/**
	 * Switch on
	 */
	void on();
	
	/**
	 * Switch off
	 */
	void off();
	
	/**
	 * Toggle switch state
	 */
	void toggle();
	
	/**
	 * Set the switch state
	 * 
	 * @param state true for on
	 */
	void setState(in boolean state);
};
