/**
 * This interface defines a warning device
 * 
 * @author <a href="mailto:emericv@mbedsys.org">Emeric Verschuur</a>
 * Copyright 2014 MbedSYS
 */
interface Warning {

	/**
	 * Warning state
	 *            <ul>
	 *            <li>IDLE: warning stopped</li>
	 *            <li>MAINTENANCE: warning in maintenance mode</li>
	 *            <li>Other value greater than zero: warning active for a
	 *            specified time in seconds</li>
	 *            </ul>
	 */
	readonly attribute long mode;

	/**
	 * Warning idle
	 */
	const unsigned long IDLE = 0;

	/**
	 * Warning in maintenance mode
	 */
	const unsigned long MAINTENANCE = -1;

	/**
	 * Set the mode
	 * 
	 * @param newState
	 */
	void setMode(in long newState);

};
