/*
 *   Copyright 2014 Emeric Verschuur <emericv@mbedsys.org>
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *		   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package org.sit4b.hobus;

/**
 * <p>
 * A low layer stack
 * </p>
 * <p>
 * {@link HbStackLL} is an object that represent a low layer stack. This
 * stack is set up when the core and all the high layer stacks are fully
 * initialized.
 * </p>
 * 
 * @author <a href="mailto:emericv@mbedsys.org">Emeric Verschuur</a> Copyright
 *         2014 MBEDSYS SAS
 */
public interface HbStackLL {
	/**
	 * Service family property key name
	 * <p>
	 * This property is the name of the service family that this stack will able
	 * to add/provide
	 * </p>
	 */
	public static final String SERVICE_FAMILY_NAME = "service.family";

	/**
	 * Setup this stack. This method is called when the core and all the stacks
	 * are fully initialized
	 * 
	 * @param stackContext
	 *            Stack context
	 */
	void setup(HbStackLLContext stackContext) throws Exception;

	/**
	 * This method is called when a service is used/generated by this stack is
	 * restored
	 * 
	 * @param service
	 *            reference to the service
	 */
	void serviceRestore(HbServiceInternalLL service);

	/**
	 * This method is called when a new service is leaved
	 * 
	 * @param service
	 *            reference to the service
	 */
	void serviceLeave(HbServiceInternalLL service);
}
